name: BuildCI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]  
  workflow_dispatch:
    workflows: ["Deploy"]
    types:
      - completed
      
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: make clean
        run: make clean
      - name: make 
        run: make 
